import type { Metadata } from "next";
import "../styles/globals.css"; // Importando o arquivo CSS global


export const metadata: Metadata = {
  title: "Cave-Echos",
  description: "Generated by create next app",
  icons: [
    {
      url: "/favicon.ico",
      rel: "icon",
    }
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
